// src/frameworks/react/App.js
import React, { Component } from "react";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = { ...props.state };
  }

  render() {
    const { state } = this;
    const { commands: { add, setName } } = this.props;
    const onChange = event => {
      setName(event.target.value);
    };
    return (
      <div className="App">
        <h1>Hello {state.name}</h1>
        <input value={state.name} onChange={onChange}></input>
        <p>{state.name.length}</p>
        <p>{state.count}</p>
        <button onClick={add}>My button</button>
      </div>
    );
  }
}

export default App;

// src/frameworks/vue/App.vue
<template>
  <div id="app">
    <h1>{{state.name}}</h1>
    <input
      :value="state.name"
      @input="setName"
    />
    <p>{{length}}</p>
    <p>{{state.count}}</p><button @click="commands.add">My button</button>
  </div>
</template>

<script>
export default {
  props: {
    state: {
      type: Object,
      required: true
    },
    commands: {
      type: Object,
      required: true
    }
  },
  name: "app",
  methods: {
    setName(event) {
      this.commands.setName(event.target.value);
    }
  },
  computed: {
    length() {
      return this.state.name.length;
    }
  }
};
</script>

<style>
html {
  height: 100%;
}

body {
  height: 100%;
  overflow: hidden;
}
</style>
